Repository apache/openwhisk-wskdeploy, pull requests merged in 2018-06, with the labels that each got.

#948 Transition specification to markdown/html and move all PDFs under archive dir.
  specification/README.md
  specification/archive/openwhisk_v0.9.1.pdf
  specification/archive/openwhisk_v0.9.2.pdf
  specification/html/images/conceptual_manifest_file_creation.png
  specification/html/images/conceptual_manifest_file_deployment.png
  specification/html/images/conceptual_programming_model.png
  specification/html/images/images.md
  specification/html/spec_definitions.md
  specification/html/spec_entity_naming_and_namespacing.md
  specification/html/spec_grammar.md
  specification/html/spec_history.md
  specification/html/spec_intro.md
  specification/html/spec_package_processing.md
  specification/html/spec_parameter_types.md
  specification/html/spec_programming_model.md
  specification/html/spec_types.md
Labels: documentation, review, specification

#946 runtimes
  cmd/export.go
  cmd/root.go
  conductor/conductor.go
  conductor/conductor_test.go
  dependencies/dependencies.go
  dependencies/dependencies_test.go
  dependencies/gitreader.go
  deployers/manifestreader.go
  deployers/manifestreader_test.go
  deployers/servicedeployer.go
  parsers/manifest_parser.go
  parsers/manifest_parser_test.go
  runtimes/runtimes.go
  runtimes/runtimes.json
  runtimes/runtimes_test.go
  tests/src/integration/common/wskdeploy.go
  utils/misc.go
  utils/misc_test.go
  webaction/webaction.go
  wskderrors/wskdeployerror.go
  wski18n/i18n_ids.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
Labels: review

#951 Adding support for API path parameters and repsonse type HTTP
  deployers/manifestreader.go
  deployers/servicedeployer.go
  parsers/manifest_parser.go
  parsers/manifest_parser_test.go
  parsers/yamlparser.go
  tests/dat/manifest_data_compose_api_records.yaml
  tests/dat/manifest_validate_trigger_action_rule_grammar.yaml
  tests/src/integration/apigateway/apigateway_test.go
  tests/src/integration/apigateway/manifest-apis-with-params.yaml
  tests/src/integration/apigateway/manifest.yml
  wski18n/i18n_ids.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
  wskprint/console.go
Labels: review

#918 Adds support for api export
  cmd/export.go
  tests/src/integration/export/export_test.go
  tests/src/integration/export/manifest_apiexp.yaml
Labels: wip
