Repository apache/openwhisk-wskdeploy, pull requests merged in 2018-03, with the labels that each got.

#765 Update deploymentreader.go tests and fix bind logic.
  .travis.yml
  cmd/report.go
  cmd/version.go
  deployers/deploymentreader.go
  deployers/deploymentreader_test.go
  deployers/servicedeployer.go
  parsers/manifest_parser.go
  parsers/yamlparser.go
  tests/dat/deployment-deploymentreader-test-packages.yml
  tests/dat/deployment_deploymentreader_packages_bind_trigger.yml
  tests/dat/deployment_deploymentreader_project_bind_trigger.yml
  tests/src/integration/validate-action-annotations/deployment-with-invalid-annotations.yaml
  tests/src/integration/validate-action-annotations/validate-action-annotations_test.go
  utils/conversion.go
  wski18n/i18n_ids.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
  wskprint/console.go
Labels: review

#785 Add trace support, include -trace flag and -v for go test.
  README.md
  cmd/root.go
  deployers/deploymentreader.go
  deployers/deploymentreader_test.go
  deployers/manifestreader_test.go
  parsers/manifest_parser.go
  utils/flags.go
  wski18n/i18n_ids.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
  wskprint/console.go
Labels: review

#784 Adding support for package binding from any namespace and declaring public packages
  parsers/manifest_parser.go
  parsers/manifest_parser_test.go
  parsers/yamlparser.go
  tests/dat/manifest_data_compose_dependencies.yaml
  tests/dat/manifest_data_compose_packages.yaml
  utils/dependencies.go
  utils/dependencies_test.go
  wski18n/i18n_ids.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
Labels: review

#789 Add assets annotation tags when assets exported
  parsers/yamlparser.go
Labels: review

#800 Display error message for each missing wskprop value.
  deployers/manifestreader.go
  deployers/servicedeployer.go
  deployers/whiskclient.go
  deployers/whiskclient_test.go
  wskderrors/wskdeployerror.go
  wskenv/environment.go
Labels: review

#790 Add support to export binary (zip and jar) actions
  cmd/export.go
  parsers/manifest_parser.go
  utils/fileoperations.go
  wski18n/i18n_ids.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
Labels: enhancement, review

#801 Adding Docker and Native support
  parsers/manifest_parser.go
  parsers/manifest_parser_test.go
  parsers/yamlparser.go
  tests/dat/manifest_data_compose_actions_for_docker.yaml
  tests/src/integration/docker/actions/bash/exec
  tests/src/integration/docker/actions/exec.zip
  tests/src/integration/docker/actions/go/exec
  tests/src/integration/docker/actions/go/sample.go
  tests/src/integration/docker/docker_test.go
  tests/src/integration/docker/manifest.yaml
  utils/misc.go
  utils/runtimes.go
Labels: review

#807 Deprecating Interactive Mode and introducing Preview
  cmd/export.go
  cmd/report.go
  cmd/root.go
  cmd/root_test.go
  deployers/servicedeployer.go
  deployers/whiskclient.go
  deployers/whiskclient_test.go
  docs/wskdeploy_configuring.md
  docs/wskdeploy_faq.md
  docs/wskdeploy_package_minimal.md
  parsers/manifest_parser.go
  tests/src/integration/common/wskdeploy.go
  utils/flags.go
  utils/misc.go
  wski18n/i18n_ids.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
Labels: review

#812 Change the gradle build to use the gogradle plugin
  .travis.yml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: wip

#816 Multiple Project Management, adding sync command, and undeploy just using Project Name
  Godeps/Godeps.json
  cmd/root.go
  cmd/sync.go
  deployers/manifestreader.go
  deployers/projectreader.go
  deployers/servicedeployer.go
  parsers/manifest_parser.go
  parsers/manifest_parser_test.go
  tests/src/integration/common/wskdeploy.go
  tests/src/integration/managed-deployment/06-manifest-with-dependency.yaml
  tests/src/integration/managed-deployment/07-manifest-with-single-dependency.yaml
  tests/src/integration/managed-deployment/08-manifest-with-dependencies-on-whisk-system.yaml
  tests/src/integration/managed-deployment/managed-deployment_test.go
  utils/flags.go
  utils/managedannotations.go
  wski18n/i18n_ids.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
Labels: review

#823 Adding documentation on Sync And Adding package binding to any /<namespace>/<package>
  deployers/servicedeployer.go
  docs/sync_projects_between_client_and_server.md
  tests/src/integration/managed-deployment/06-manifest-with-single-dependency.yaml
  tests/src/integration/managed-deployment/07-manifest-with-dependency.yaml
  tests/src/integration/managed-deployment/managed-deployment_test.go
  wski18n/i18n_resources.go
Labels: review

#831 Fix location of new API GW example doc.
  docs/wskdeploy_apigateway_helloworld.md
Labels: review

#832 Replacing pritidesai with apache in GitHub repos
  docs/sync_projects_between_client_and_server.md
  tests/src/integration/dependency/README.md
  tests/src/integration/managed-deployment/06-manifest-with-single-dependency.yaml
  tests/src/integration/managed-deployment/07-manifest-with-dependency.yaml
  tests/usecases/github/README.md
  tests/usecases/slack/README.md
Labels: review

#828 Extend export to support project with dependencies
  cmd/export.go
  parsers/manifest_parser.go
  parsers/manifest_parser_test.go
  parsers/yamlparser.go
  tests/src/integration/common/wskdeploy.go
  tests/src/integration/export/export_test.go
  tests/src/integration/export/manifest_ext.yaml
  tests/src/integration/export/manifest_lib1.yaml
  tests/src/integration/export/manifest_lib2.yaml
  tests/src/integration/export/src/greeting.js
  utils/managedannotations.go
  wski18n/i18n_ids.go
Labels: changes requested, wip
