Repository apache/openwhisk-wskdeploy, pull requests merged in 2018-05, with the labels that each got.

#886 adding license files
  licenses/LICENSE-cobra.txt
  licenses/LICENSE-color.txt
  licenses/LICENSE-gocolorable.txt
  licenses/LICENSE-goi18n.txt
  licenses/LICENSE-goprettyjson.txt
  licenses/LICENSE-jibberjabber.txt
  licenses/LICENSE-openwhiskclientgo.txt
  licenses/LICENSE-viper.txt
  licenses/LICENSE-yaml.txt
Labels: review

#893 adding env. variables in action function
  parsers/manifest_parser.go
  parsers/manifest_parser_test.go
  tests/dat/manifest_data_compose_actions_for_function_with_env_variable.yaml
Labels: review

#894 adding list of YAML key/values which supports env. variables
  docs/wskdeploy_interpolation.md
Labels: review

#890 Resolves issue #880
  cmd/export.go
  parsers/yamlparser.go
Labels: changes requested, wip

#897 Fix all files with Hash license header to fix typo.
  CONTRIBUTING.md
  DEPENDENCIES.md
  README.md
  docs/creating_tagged_releases.md
  docs/export.md
  docs/programming_guide.md
  docs/sync_projects_between_client_and_server.md
  docs/wskdeploy_action_advanced_parms.md
  docs/wskdeploy_action_env_var_parms.md
  docs/wskdeploy_action_fixed_parms.md
  docs/wskdeploy_action_helloworld.md
  docs/wskdeploy_action_runtime.md
  docs/wskdeploy_action_typed_parms.md
  docs/wskdeploy_apigateway_helloworld.md
  docs/wskdeploy_apigateway_sequence.md
  docs/wskdeploy_configuring.md
  docs/wskdeploy_debugging.md
  docs/wskdeploy_example_template.md
  docs/wskdeploy_faq.md
  docs/wskdeploy_interpolation.md
  docs/wskdeploy_package_minimal.md
  docs/wskdeploy_sequence_basic.md
  docs/wskdeploy_triggerrule_basic.md
  docs/wskdeploy_triggerrule_trigger_bindings.md
  specification/README.md
  specification/diagrams/README.md
  specification/html/spec_actions.md
  specification/html/spec_index.md
  specification/html/spec_normative_refs.md
  specification/html/spec_packages.md
  specification/html/spec_parameters.md
  specification/html/spec_sequences.md
  specification/html/spec_shared_entity_schema.md
  specification/html/spec_trigger_rule.md
  specification/html/spec_types.md
  specification/images/images.md
  tests/README.md
  tests/apps/openwhisk-githubslackbot/README.md
  tests/apps/owbp-cloudant-trigger/README.md
  tests/src/integration/alarmtrigger/README.md
  tests/src/integration/cloudant/README.md
  tests/src/integration/dependency/README.md
  tests/src/integration/helloworld/README.md
  tests/src/integration/message-hub/README.md
  tests/src/integration/runtimetests/src/helloworld/node_modules/string-format/README.md
  tests/src/integration/zipaction/actions/cat/node_modules/cat/README.md
  tests/usecases/dependency/README.md
  tests/usecases/github/README.md
  tests/usecases/slack/README.md
  tests/usecases/triggerrule/README.md
Labels: apache, documentation

#907 Fix makefile ASF header & use ICF as example of curl usage.
  Dockerfile
  Makefile
  docs/examples/deployment_hello_world_triggerrule_bindings.yaml
  docs/examples/deployment_hello_world_triggerrule_unbound.yaml
  docs/examples/manifest_hello_world.yaml
  docs/examples/manifest_hello_world_advanced_parms.yaml
  docs/examples/manifest_hello_world_apigateway.yaml
  docs/examples/manifest_hello_world_env_var_parms.yaml
  docs/examples/manifest_hello_world_fixed_parms.yaml
  docs/examples/manifest_hello_world_runtime.yaml
  docs/examples/manifest_hello_world_triggerrule.yaml
  docs/examples/manifest_hello_world_triggerrule_unbound.yaml
  docs/examples/manifest_hello_world_typed_parms.yaml
  docs/examples/manifest_package_minimal.yaml
  docs/examples/manifest_sequence_basic.yaml
  docs/wskdeploy_action_runtime.md
  tests/dat/manifest_data_compose_packages.yaml
  tests/src/integration/validate-manifest-deployment-file-extensions/random-name-1.yaml
  tests/src/integration/validate-manifest-deployment-file-extensions/random-name-2.yaml
  tests/src/integration/validate-manifest-deployment-file-extensions/yaml-deployment-with-yml-manifest.yaml
  tests/src/integration/validate-manifest-deployment-file-extensions/yaml-manifest-with-yml-deployment.yaml
  tests/src/integration/validate-packages-in-manifest/deployment.yaml
  tests/src/integration/validate-packages-in-manifest/manifest.yaml
  tests/src/integration/validate-project/deployment.yaml
  tests/src/integration/validate-project/manifest.yaml
  tests/src/integration/validatePackagesInDeployment/actions/helloworld.js
  tests/src/integration/validatePackagesInDeployment/deployment.yaml
  tests/src/integration/validatePackagesInDeployment/manifest.yaml
  tests/src/integration/validateSequencesCreation/actions/function.js
  tests/src/integration/webaction/src/greeting.js
  tests/src/integration/websequence/manifest.yaml
  tests/src/integration/websequence/src/greeting.js
  tests/src/integration/zipaction/actions/cat/node_modules/cat/bin.js
  tests/src/integration/zipaction/actions/cat/node_modules/cat/example.js
  tests/src/integration/zipaction/actions/cat/node_modules/cat/index.js
  tests/usecases/api-gateway/actions/fire/index.js
  tests/usecases/api-gateway/simple_api_manifest.yaml
  tests/usecases/badyaml/deployment.yaml
  tests/usecases/badyaml/manifest.yaml
  tests/usecases/dependency/manifest.yaml
  tests/usecases/github/deployment.yaml
  tests/usecases/github/manifest.yaml
  tests/usecases/github/src/print-github-commits.js
  tests/usecases/slack/actions/post-to-slack.js
  tests/usecases/slack/deployment.yaml
  tests/usecases/slack/manifest.yaml
  tests/usecases/triggerrule/src/greeting.js
  tools/travis/docker/Dockerfile
  wski18n/README.md
Labels: apache, documentation

#912 Fix travis yaml file asf header, change to mini.
  .travis.yml
Labels: apache

#915 Fix last few files missing correct ASF header and EOF errors.
  docs/examples/manifest_hello_world_apigateway_sequence.yml
  docs/examples/src/hello.py
  tests/src/integration/export/manifest_2pack.yaml
  tests/src/integration/managed-deployment/05-manifest-headless.yaml
  tests/src/integration/runtimetests/src/helloworld/node_modules/string-format/lib/string-format.js
  tests/usecases/triggerrule/deployment.yml
  tests/usecases/triggerrule/manifest.yml
Labels: apache

#921 Add ASF license header to .gradle files.
  ansible/environments/local/group_vars/all
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  tests/dat/wskpropsnokeycert
Labels: apache, review

#937 getting rid of node modules
  tests/src/integration/docker/actions/exec.zip
  tests/src/integration/runtimetests/src/helloworld/helloworld.zip
  tests/src/integration/runtimetests/src/helloworld/index.js
  tests/src/integration/runtimetests/src/helloworld/node_modules/string-format/README.md
  tests/src/integration/runtimetests/src/helloworld/node_modules/string-format/lib/string-format.js
  tests/src/integration/runtimetests/src/helloworld/node_modules/string-format/package.json
  tests/src/integration/runtimetests/src/helloworld/package.json
  tests/src/integration/validate-packages-in-manifest/actions/Hello.java
Labels: review

#939 introducing deployment to IBM cloud functions using exported manifest
  tests/src/integration/export/export_test.go
Labels: review

#941 commenting out TestExportHelloWorld as its unstable in Travis
  tests/src/integration/export/export_test.go
Labels: review

#943 Add the help message, if manifest file is not accesible to wskdeploy and undeploy
  cmd/report.go
  cmd/root.go
  cmd/sync.go
  cmd/undeploy.go
Labels: changes requested

#945 Update Travis to use ASF-Release.cfg
  tools/travis/scancode.sh
Labels: apache, review
