Repository apache/openwhisk-wskdeploy, pull requests merged in 2018-04, with the labels that each got.

#834 Adding support for conductor, web sequences, and converting to web actions for api gateway
  deployers/manifestreader.go
  parsers/manifest_parser.go
  parsers/manifest_parser_test.go
  parsers/yamlparser.go
  tests/dat/manifest_data_compose_actions_for_web_and_web_export.yaml
  tests/dat/manifest_data_compose_api_records.yaml
  tests/src/integration/apigateway/manifest.yml
  tests/src/integration/conductor/actions/increment.js
  tests/src/integration/conductor/actions/triple.js
  tests/src/integration/conductor/actions/tripleAndIncrement.js
  tests/src/integration/conductor/conductor_test.go
  tests/src/integration/conductor/manifest.yaml
  tests/src/integration/websequence/manifest.yaml
  tests/src/integration/websequence/src/greeting.js
  tests/src/integration/websequence/websequence_test.go
  utils/conductor.go
  utils/conductor_test.go
  utils/misc.go
  utils/webaction.go
  wski18n/i18n_ids.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
Labels: review

#853 Update spec. to include release 0.9.2 features as revision 2.
  specification/openwhisk_v0.9.2.pdf
Labels: review

#864 upgrading go client version
  Godeps/Godeps.json
  build.gradle
Labels: review

#863 Refactoring ManifestReader
  cmd/root.go
  deployers/manifestreader.go
  deployers/manifestreader_test.go
  deployers/servicedeployer.go
  parsers/manifest_parser.go
  tests/dat/manifest_validate_action_all.yaml
  tests/dat/manifest_validate_dependencies.yaml
  tests/dat/manifest_validate_dependencies_bogus.yaml
  tests/dat/manifest_validate_package_inputs_and_annotations.yaml
  tests/dat/manifest_validate_rules_bogus.yaml
  tests/dat/manifest_validate_sequences_bogus.yaml
  tests/dat/manifest_validate_triggers_bogus.yaml
  utils/dependencies.go
  utils/gitreader.go
  wski18n/i18n_ids.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
Labels: review

#867 fixing docker image name
  tests/src/integration/docker/manifest.yaml
Labels: review

#873 Fix example with old package syntax.
  docs/examples/manifest_package_minimal.yaml
  docs/wskdeploy_package_minimal.md
Labels: bug, documentation

#875 Add scancode using ASF config. to Travis build.
  tools/travis/cloneutils.sh
  tools/travis/scancode.sh
Labels: build

#877 Adding annotation conversion
  parsers/manifest_parser.go
  parsers/manifest_parser_test.go
  tests/dat/manifest_data_compose_actions_for_annotations.yaml
  utils/conversion.go
  utils/conversion_test.go
Labels: review

#882 Add ASF license headers to API Gateway integration test's javascript …
  tests/src/integration/apigateway/src/delete-books.js
  tests/src/integration/apigateway/src/get-books.js
  tests/src/integration/apigateway/src/list-members.js
  tests/src/integration/apigateway/src/post-books.js
  tests/src/integration/apigateway/src/put-books.js
Labels: apache, documentation, review
