Repository apache/openwhisk-wskdeploy, pull requests merged in 2021-03, with the labels that each got.

#1123 Upgrade Gradle/Wrapper to latest version
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: build

#1124 Update openwhisk-client-go to release 1.1.0 as well as other pkg dependencies
  DEPENDENCIES.md
  README.md
  go.mod
  go.sum
Labels: build

#1126 Prep. for potential 1.2.0 release
  CHANGELOG.md
  NOTICE.txt
  go.mod
  go.sum
Labels: build, documentation

#1127 chore: fix spelling
  deployers/deploymentreader_test.go
  deployers/whiskclient_test.go
  docs/sync_projects_between_client_and_server.md
  docs/wskdeploy_action_env_var_parms.md
  docs/wskdeploy_apigateway_http.md
  docs/wskdeploy_apigateway_http_sequence.md
  docs/wskdeploy_apigateway_open_api_spec.md
  docs/wskdeploy_faq.md
  docs/wskdeploy_sequence_basic.md
  parsers/manifest_parser.go
  specification/html/spec_packages.md
  specification/html/spec_rule.md
  specification/html/spec_trigger.md
  tests/apps/openwhisk-githubslackbot/actions/find-delayed-pull-requests.js
  tests/apps/openwhisk-githubslackbot/actions/track-pull-requests.js
  utils/file.go
  utils/misc_test.go
  utils/validation.go
  utils/zip.go
  wskenv/environment_test.go
  wski18n/i18n_resources.go
  wski18n/resources/en_US.all.json
Labels: changes requested, documentation, enhancement, help wanted
